on:
  push:
    branches:
      - main
      
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - run: echo "List contents of ./kjell/hello_world"
        working-directory: devops-exam/kjell/hello_world
        run: ls -al
      - run: echo "Print SAM template contents"
        working-directory: devops-exam/kjell/hello_world
        run: cat template.yml
      - run: sam build --use-container
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-kjell-2009 --s3-bucket pgr301-sam-bucket --capabilities CAPABILITY_IAM --region us-west-1
