name: Task2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

<<<<<<< HEAD
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        dockerfile: Dockerfile
        container-name: task2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Build Docker image
      run: |
        docker build -t task2:${{ github.sha }} .
        docker tag task2:${{ github.sha }} 244530008913.dkr.ecr.eu-west-1.amazonaws.com/task2:${{ github.sha }}
        docker tag task2:${{ github.sha }} 244530008913.dkr.ecr.eu-west-1.amazonaws.com/task2:latest

    - name: Authenticate Docker to AWS ECR
      run: aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com

    - name: Push Docker image to AWS ECR
      run: |
        docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/task2:${{ github.sha }}
        docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/task2:latest
=======
      - name: Build and push Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build -t . 
          docker tag 244530008913.dkr.ecr.eu-west-1.amazonaws.com/2009-jams:$rev
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/2009-jams:$rev
>>>>>>> parent of 8595939 (fixed big yikes and trying again task2)
